#!/bin/ash

DAEMON='powqutyd'
PID=`pidof ${DAEMON}`
OUTPUT_DIR="/mnt/sdcard/"
LOGFILE="${OUTPUT_DIR}pqpack.log"
PACKER="bzip2"

OUTPUT_FILE_HOST="$(uname -n)-"
OUTPUT_FILE_EXT=".bz2"

STDOUT=1
MQTT="10.10.4.5"

echod() {
	local MSG_TS="$(date +%s)"
	local MSG_DATE="$(date +'%d.%m.%Y %H:%M:%S')"
	local MSG_HOST="$(uname -n)"
	local TEXT="[$(date +'%d.%m.%Y %H:%M:%S')] $@"
	[[ $STDOUT -ne 0 ]] && echo "$TEXT"
	echo "${TEXT}" >> "${LOGFILE}"
	[[ -n "$MQTT" ]] && mosquitto_pub -t 'measurement/pqpack' -q 0 --quiet -h "${MQTT}" -m "${MSG_TS},${MSG_DATE},${MSG_HOST},$@" &
	return 0
}

ls -1 ${OUTPUT_DIR}${OUTPUT_FILE_HOST}*powquty_raw*.log | head -n -1 | while IFS="" read -r file
do
	[[ -f "${file}${OUTPUT_FILE_EXT}" ]] && echod "file $(basename ${file})${OUTPUT_FILE_EXT} already exists, skipping" && continue
	${PACKER} "${file}" &>/dev/null
	RES=$?
	if [ $RES -eq 0 ]; then
		echod "compressed: ${file}"
	else
		echod "faied compressing ${file}"
	fi
done
