#!/bin/ash
WAIT=${1:-5}
MQTT=${2:-10.10.4.5}
sleep ${WAIT} # offset

detect_usb_device() {
	DEVFOUND=`ls -1 /dev/ttyACM* 2>/dev/null | head -n 1`
	if [ -z "${DEVFOUND}" ]; then
		echo "-"
		return 1
	fi
	echo "${DEVFOUND}"
	return 0
}

DAEMON='powqutyd'
HOSTNAME="$(uname -n)"
pidof "${DAEMON}" >/dev/null && PQDAEMON=1 || PQDAEMON=0
DFOUT=`df -m /mnt/sdcard | tail -n 1 | awk '{print $2","$3","$4}'`
USBDEV="$(detect_usb_device)"
MSG="$(date +%s),${HOSTNAME},${PQDAEMON},${DFOUT},${USBDEV}"

mosquitto_pub -t 'measurement/pqstatus' -q 0 --quiet -h "${MQTT}" -m "${MSG}"
