#!/bin/sh

PROD_ID="1afe/9/100"
SYMLINK="WeSense0"

if [ "${PRODUCT}" = "${PROD_ID}" ]; then
	if [ "${ACTION}" = "add" ]; then
		DEVICE_NAME=$(ls /sys/${DEVPATH}/tty/ | head -n 1)
		if [ -z ${DEVICE_NAME} ]; then
			logger -t Hotplug warning: DEVICE_NAME is empty
			exit
		fi
		ln -s /dev/$DEVICE_NAME /dev/${SYMLINK}
		logger -t Hotplug symlink from /dev/$DEVICE_NAME to /dev/${SYMLINK} created
	fi
	if [ "${ACTION}" = "remove" ]; then
		rm /dev/${SYMLINK}
		logger -t Hotplug symlink /dev/${SYMLINK} removed
	fi
fi

